spring:
    datasource:
        url: jdbc:mysql://localhost:3306/tempest_vortex_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        username: root
        password: Gudmord92!
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            maximum-pool-size: 20
            minimum-idle: 5
            idle-timeout: 30000
    jpa:
        hibernate:
            jdbc:
                batch_size: 25
                order_inserts: true
                order_updates: true
                batch_versioned_data: true
            ddl-auto: update
        database-platform: org.hibernate.dialect.MySQLDialect
        show-sql: true
        generate-ddl: true
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
    flyway:
      repair-on-migrate: true